version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_VERSION}
    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
      - ./scrtips:/scripts
